name: Deploy webapp to EC2

on:
  push:
    branches: [ "main" ]
    paths:
      - "webapp/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init (to read outputs)
        run: terraform init -input=false


      - name: Get public IPs
        id: get_ips
        run: echo "ips=$(terraform output -json public_ips)" >> $GITHUB_OUTPUT


      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ips=$(echo '${{ steps.get_ips.outputs.ips }}' | jq -r '.[]')
          for ip in $ips; do
            ssh-keyscan -H $ip >> ~/.ssh/known_hosts || true
          done


      - name: Rsync webapp to all EC2 instances
        run: |
          ips=$(echo '${{ steps.get_ips.outputs.ips }}' | jq -r '.[]')
          for ip in $ips; do
            echo "Deploying to $ip"
            rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" --delete ../webapp/ ubuntu@$ip:/var/www/html/
          done
