name: Deploy webapp to EC2

on:
  push:
    branches: [ "main" ]
    paths:
      - "webapp/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init (to read outputs)
        run: terraform init -input=false

      - name: Get public IP
        id: get_ip
        run: echo "ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ steps.get_ip.outputs.ip }} >> ~/.ssh/known_hosts || true

      - name: Rsync webapp to EC2
        run: |
          echo "Deploying to ${{ steps.get_ip.outputs.ip }}"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" --delete ../webapp/ ubuntu@${{ steps.get_ip.outputs.ip }}:/var/www/html/
          #
